# Create an overlap raster script for each insect species from GLM
# Jeff Oliver
# jcoliver@arizona.edu
# 2021-07-08

SCRIPTTYPE="overlap-raster"
MODEL="glm"
MODELUPPER=$(echo $MODEL | tr '[:lower:]' '[:upper:]')
PRODUCT="overlap raster"

# Read the file with insect names in as an array, skipping the header row 
# (hence -n +2 in call to tail); need to also sort & pull out only unique 
# values as an insect species may be represented multiple times in file
readarray -t NAMES < <(tail -n +2 data/insect-host.csv | cut -d "," -f1 | sort | uniq)

for NAME in "${NAMES[@]}"
do
    # echo "$LINE"
    # Split NAME into constituent parts
    NAME=($NAME)  # turns it into an array
    GENUS=${NAME[0]}
    SPECIES=${NAME[1]}
    # echo "GENUS: ${GENUS}, SPECIES: ${SPECIES}"
    
    # For the filename, want genus to be lower case
    GENUSLOWER=$(echo $GENUS | tr '[:upper:]' '[:lower:]')
    FILENAME="scripts/${GENUSLOWER}_${SPECIES}-${SCRIPTTYPE}-${MODEL}.R"

    # Read in the template file contents into the MODELFILE variable, 
    # skipping very first line
    TEMPLATE="templates/template-${SCRIPTTYPE}-${MODEL}-building.R"
    MODELFILE=$(cat "$TEMPLATE" | tail -n +2)

    # Add lines at top of file explaining script & message warning against 
    # editing
    MESSAGE="# This file is auto-generated by build-${SCRIPTTYPE}-${MODEL}-files.sh. Do NOT edit."
    MODELFILE=$(echo -e "# Generate ${PRODUCT} for ${GENUS} ${SPECIES} from ${MODELUPPER}\n${MESSAGE}\n${MODELFILE}")

    # Use sed to find/replace GENUS/SPECIES values and write to file
    echo "${MODELFILE}" | \
      sed "s/GENUS/${GENUS}/g" | \
      sed "s/SPECIES/${SPECIES}/g" > "$FILENAME"
    echo "Wrote to ${FILENAME}"

done;

