# Create a script for each species for running (or for Maxent, just saving) 
# SDMs using all available data
# Jeff Oliver
# jcoliver@arizona.edu
# 2021-06-02

SCRIPTNUM="2"
SCRIPTTYPE="SDMs-full"
PRODUCT="SDM models using all available data"

# If script is called with -v flag, will print messages after writing each file
while getopts v flag
do
    case "${flag}" in
        v) verbose=true;;
    esac
done

# Read the file with organism names in as an array, skipping the header row 
# (hence -n +2 in call to tail)
readarray -t NAMES < <(tail -n +2 data/gbif-reconcile.csv)

# Iterate over all the types of models (e.g. glm, svm)
for LINE in "${NAMES[@]}"
do
  # echo "$LINE"
  # Create an array out of that line
  IFS="," read -r -a ONENAME <<< "${LINE}"

  # Extract genus & species name
  GENUSSPECIES=$(echo "${ONENAME[3]}" | sed 's/\"//g')
  GENUS=$(echo "$GENUSSPECIES" | cut -d' ' -f 1)
  SPECIES=$(echo "$GENUSSPECIES" | cut -d' ' -f 2)
  # echo "GENUS: ${GENUS}, SPECIES: ${SPECIES}"

  # For the filename, want genus to be lower case
  GENUSLOWER=$(echo $GENUS | tr '[:upper:]' '[:lower:]')
  FILENAME="src/indiv/${GENUSLOWER}_${SPECIES}-${SCRIPTNUM}-${SCRIPTTYPE}.R"
  
  # Read in the template file contents into the SCRIPTBODY variable, 
  # skipping first two lines
  TEMPLATE="templates/template-${SCRIPTNUM}-${SCRIPTTYPE}.R"
  SCRIPTBODY=$(cat "$TEMPLATE" | tail -n +2)
  
  # Add lines at top of file explaining script & message warning against 
  # editing
  MESSAGE="# This file is auto-generated by build-scripts-${SCRIPTNUM}-${SCRIPTTYPE}.sh. Do NOT edit."
  # TODO: Assumes SCRIPTBODY contains no newline characters (\n)
  SCRIPTBODY=$(echo -e "# Generate ${PRODUCT} for ${GENUS} ${SPECIES}\n${MESSAGE}\n${SCRIPTBODY}")

  # Use sed to find/replace GENUS/SPECIES values and write to file
  echo "${SCRIPTBODY}" | \
    sed "s/GENUS/${GENUS}/g" | \
    sed "s/SPECIES/${SPECIES}/g" > "$FILENAME"
    
  # If verbose, print out message
  if [ "$verbose" = true ] ; then
      echo "Wrote to ${FILENAME}"
  fi
  
done; # end iterating over all species names
